## Deliverable 3. Create a Travel Itinerary Map.

In [1]:
# Dependencies and Setup
import pandas as pd
import requests
import gmaps

# Import API key
from config import g_key

# Configure gmaps
gmaps.configure(api_key=g_key)

In [2]:
# 1. Read the WeatherPy_vacation.csv into a DataFrame.
vacation_df = pd.read_csv("../Vacation_Search/WeatherPy_vacation.csv")
vacation_df.head()

City_ID       City Country  Max Temp Current Description      Lat  \
0        2   Hermanus      ZA     67.89     overcast clouds -34.4187   
1        6  Mahebourg      MU     79.09    scattered clouds -20.4081   
2        8     Castro      BR     77.88     overcast clouds -24.7911   
3        9  Busselton      AU     52.05       broken clouds -33.6500   
4       10      Hobyo      SO     79.05       broken clouds   5.3505   

        Lng                          Hotel Name  
0   19.2345          Misty Waves Boutique Hotel  
1   57.7000  Shandrani Beachcomber Resort & Spa  
2  -50.0119                      CHACARA BAILLY  
3  115.3333             Observatory Guest House  
4   48.5268         Halane Hotel and Restaurent

In [12]:
# 2. Using the template add the city name, the country code, the weather description and maximum temperature for the city.
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Weather Description</dt><dd>{Current Description}</dd>
<dt>Max Temp</dt><dd>{Max Temp} °F</dd>
</dl>
"""
# 3a. Get the data from each row and add it to the formatting template and store the data in a list.
vacation_info = [info_box_template.format(**row) for index, row in vacation_df.iterrows()]

# 3b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = vacation_df[["Lat", "Lng"]]

In [13]:
# 4a. Add a marker layer for each city to the map.
locations = vacation_df[["Lat", "Lng"]]
max_temp = vacation_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=max_temp,dissipating=False,
             max_intensity=300, point_radius=4)
marker_layer = gmaps.marker_layer(locations, info_box_content=vacation_info)
fig.add_layer(heat_layer)
fig.add_layer(marker_layer)
# 4b. Display the figure
fig

Figure(layout=FigureLayout(height='420px'))

In [28]:
# From the map above pick 4 cities and create a vacation itinerary route to travel between the four cities. 
# 5. Create DataFrames for each city by filtering the 'vacation_df' using the loc method. 
# Hint: The starting and ending city should be the same city.

vacation_start = vacation_df.loc[(vacation_df['City']=='Sunland Park')
                                & (vacation_df['Hotel Name']=='SpringHill Suites by Marriott El Paso')]
vacation_end = vacation_df.loc[(vacation_df['City']=='Sunland Park')
                              & (vacation_df['Hotel Name']=='SpringHill Suites by Marriott El Paso')]
vacation_stop1 = vacation_df.loc[(vacation_df['City']=='Ocampo')
                              & (vacation_df['Hotel Name']=='Hotel Estancia del Vaquero')]
vacation_stop2 = vacation_df.loc[(vacation_df['City']=='San Patricio')
                                & (vacation_df['Hotel Name']=='Motel 6 Sinton, TX')] 
vacation_stop3 = vacation_df.loc[(vacation_df['City']=='Ixtapa')
                                & (vacation_df['Hotel Name']=='Hotel Plaza Providencia')] 

In [29]:
# 6. Get the latitude-longitude pairs as tuples from each city DataFrame using the to_numpy function and list indexing.
start = pd.DataFrame(vacation_start[["Lat", "Lng"]]).to_numpy()
end = pd.DataFrame(vacation_end[["Lat", "Lng"]]).to_numpy()
stop1 = pd.DataFrame(vacation_stop1[["Lat", "Lng"]]).to_numpy()
stop2 = pd.DataFrame(vacation_stop2[["Lat", "Lng"]]).to_numpy()
stop3 = pd.DataFrame(vacation_stop3[["Lat", "Lng"]]).to_numpy()
start, stop1, stop2, stop3

(array([[  31.7965, -106.58  ]]),
 array([[  21.65, -101.5 ]]),
 array([[ 28.017 , -97.5169]]),
 array([[  20.7, -105.2]]))

In [30]:
# add the latitude/longitude
start=(31.7965, -106.58)
end=(31.7965, -106.58)
stop1=(21.65 , -101.5)
stop2=(28.017, -97.5169)
stop3=(20.7, -105.2)

In [32]:
# 7. Create a direction layer map using the start and end latitude-longitude pairs,
# and stop1, stop2, and stop3 as the waypoints. The travel_mode should be "DRIVING", "BICYCLING", or "WALKING".
fig = gmaps.figure()
itinerary_trip_plan = gmaps.directions_layer(start,end, 
                                             waypoints=[stop1,stop2,stop3],
                                             travel_mode="DRIVING")
fig.add_layer(itinerary_trip_plan)
fig



Figure(layout=FigureLayout(height='420px'))

In [33]:
# 8. To create a marker layer map between the four cities.
#  Combine the four city DataFrames into one DataFrame using the concat() function.
itinerary_df = pd.concat([vacation_start, vacation_stop1, vacation_stop2, vacation_stop3],ignore_index=True)
itinerary_df

City_ID          City Country  Max Temp Current Description      Lat  \
0      641  Sunland Park      US     55.81           clear sky  31.7965   
1      483        Ocampo      MX     67.95       broken clouds  21.6500   
2       35  San Patricio      US     61.21           clear sky  28.0170   
3      587        Ixtapa      MX     81.63           clear sky  20.7000   

        Lng                             Hotel Name  
0 -106.5800  SpringHill Suites by Marriott El Paso  
1 -101.5000             Hotel Estancia del Vaquero  
2  -97.5169                     Motel 6 Sinton, TX  
3 -105.2000                Hotel Plaza Providencia

In [34]:
# 9 Using the template add city name, the country code, the weather description and maximum temperature for the city. 
info_box_template = """
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Weather Description</dt><dd>{Current Description}</dd>
<dt>Max Temp</dt><dd>{Max Temp} °F</dd>
</dl>
"""

# 10a Get the data from each row and add it to the formatting template and store the data in a list.
itinerary_info = [info_box_template.format(**row) for index, row in itinerary_df.iterrows()]

# 10b. Get the latitude and longitude from each row and store in a new DataFrame.
itinerary_locations = itinerary_df[["Lat", "Lng"]]

In [35]:
# 11a. Add a marker layer for each city to the map.
itinerary_locations = itinerary_df[["Lat", "Lng"]]
fig = gmaps.figure(center=(31.0, -106.0), zoom_level=5)
marker_layer = gmaps.marker_layer(itinerary_locations, info_box_content=itinerary_info)
fig.add_layer(marker_layer)

# 11b. Display the figure
fig


Figure(layout=FigureLayout(height='420px'))